.TH SETBFREEUI "1" "Feb 2015" "setBfreeUI 0.8" "User Commands"
.SH NAME
setBfree \- DSP tonewheel organ Graphical User Interface
.SH SYNOPSIS
.B setBfreeUI
.SH DESCRIPTION
setBfree \- DSP tonewheel organ Graphical User Interface
.PP
setBfree is a MIDI\-controlled, software synthesizer designed to imitate
the sound and properties of the electromechanical organs and sound
modification devices that brought world\-wide fame to the names and
products of Laurens Hammond and Don Leslie.
.PP
Thes GUI takes no commandline arguments. see setBfree(1) for the 
commandline option and complete documentation.
.SH "CONFIGURATOIN FILES"
setBfreeUI reads $XDG_CONFIG_HOME/setBfree/default.cfg and
$XDG_CONFIG_HOME/setBfree/default.pgm on startup. see setBfree(1)
for details.
.SH "REPORTING BUGS"
Report bugs at <http://github.com/pantherb/setBfree/issues>.
.br
Website and manual: <http://setbfree.org>
.SH COPYRIGHT
Copyright \(co 2003\-2004 Fredrik Kilander <fk@dsv.su.se>
.br
Copyright \(co 2008\-2015 Robin Gareus <robin@gareus.org>
.br
Copyright \(co 2010 Ken Restivo <ken@restivo.org>
.br
Copyright \(co 2012 Will Panther <pantherb@setbfree.org>
.PP
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
