.TH SETBFREE-START "1" "July 2012" "setBfree-start 0.5.0" "User Commands"
.SH NAME
setBfree-start \- wrapper-script to start setBfree and vb3kb
.SH SYNOPSIS
.B setBfree-start
[\fIOPTIONS\fR]
.SH DESCRIPTION
setBfree-start \fB\-\-\fR DSP tonewheel Organ startup script
.PP
Startup script to launch setBfree, vb3kb and connect them.
All options are passed through to setBfree.
.SH "SEE ALSO"
.B setBfree(1)
.B vb3kb(1)
.SH ENVIRONMENT
VKOPTS commandline parameters to pass to vb3kb
.SH COPYRIGHT
Copyright \(co 2012 Robin Gareus
.PP
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
