// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/b_whirl#extended

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_descriptor(uint32_t index);

static const RtkLv2Description _plugin = {
	&lv2_descriptor,
	&lv2ui_descriptor
	, 1 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "setBfree Whirl Speaker" // const char *plugin_human_id
	, (const struct LV2Port[43])
	{
		{ "in", AUDIO_IN, nan},
		{ "left", AUDIO_OUT, nan},
		{ "right", AUDIO_OUT, nan},
		{ "rt_speed", CONTROL_IN, 4.000000},
		{ "hornlvl", CONTROL_IN, 0.000000},
		{ "drumlvl", CONTROL_IN, 0.000000},
		{ "drumwidth", CONTROL_IN, 1.000000},
		{ "hornrpmslow", CONTROL_IN, 40.320000},
		{ "hornrpmfast", CONTROL_IN, 423.359985},
		{ "hornaccel", CONTROL_IN, 0.161000},
		{ "horndecel", CONTROL_IN, 0.321000},
		{ "hornbrakepos", CONTROL_IN, 0.000000},
		{ "filtatype", CONTROL_IN, 0.000000},
		{ "filtafreq", CONTROL_IN, 4500.000000},
		{ "filtaq", CONTROL_IN, 2.745600},
		{ "filtagain", CONTROL_IN, -30.000000},
		{ "filtbtype", CONTROL_IN, 7.000000},
		{ "filtbfreq", CONTROL_IN, 300.000000},
		{ "filtbq", CONTROL_IN, 1.000000},
		{ "filtbgain", CONTROL_IN, -30.000000},
		{ "drumrpmslow", CONTROL_IN, 36.000000},
		{ "drumrpmfast", CONTROL_IN, 357.299988},
		{ "drumaccel", CONTROL_IN, 4.127000},
		{ "drumdecel", CONTROL_IN, 1.371000},
		{ "drumbrake", CONTROL_IN, 0.000000},
		{ "filtdtype", CONTROL_IN, 8.000000},
		{ "filtdfreq", CONTROL_IN, 811.969482},
		{ "filtdq", CONTROL_IN, 1.601600},
		{ "filtdgain", CONTROL_IN, -38.929100},
		{ "hornleak", CONTROL_IN, -16.469999},
		{ "hornradius", CONTROL_IN, 19.200001},
		{ "drumradius", CONTROL_IN, 22.000000},
		{ "hornxoff", CONTROL_IN, 0.000000},
		{ "hornzoff", CONTROL_IN, 0.000000},
		{ "micdist", CONTROL_IN, 42.000000},
		{ "hornrpm", CONTROL_OUT, nan},
		{ "drumrpm", CONTROL_OUT, nan},
		{ "hornang", CONTROL_OUT, nan},
		{ "drumang", CONTROL_OUT, nan},
		{ "guitrigger", CONTROL_IN, 0.000000},
		{ "link", CONTROL_IN, 0.000000},
		{ "micangle", CONTROL_IN, 180.000000},
		{ "hornwidth", CONTROL_IN, 1.000000},
	}
	, 43 // uint32_t nports_total
	, 1 // uint32_t nports_audio_in
	, 2 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 0 // uint32_t nports_midi_out
	, 0 // uint32_t nports_atom_in
	, 0 // uint32_t nports_atom_out
	, 40 // uint32_t nports_ctrl
	, 36 // uint32_t nports_ctrl_in
	, 4 // uint32_t nports_ctrl_out
	, 8192 // uint32_t min_atom_bufsiz
	, false // bool send_time_info
};
